#https://github.com/CocoaPods/CocoaPods/wiki/A-Podfile

platform :ios

# The following pods come from a spec repo that is not the main spec repo
# You have to run `pod repo add adamvduke https://github.com/adamvduke/PodSpecs.git`
# to add the additional spec repo
pod 'ADOAuthorizeiOS'
pod 'OAuthConsumer'
pod 'ObjCMacros'
pod 'Seriously'

# The following pods come from the main spec repo
pod 'SBJson'

target 'ADEngineBlockSpecs' do
  pod 'Cedar'
end
